### ISSUE TITLE
Unable to access OpenAPI v3 examples in hosted documentation

### ISSUE THREAD

**Issue by TomChapple** [apigovau/national-api-design-standards#1]
This issue is in regards to the hosting of this documentation rather than the documentation itself.

On the ["Getting Started" page under "Sample OpenAPI Definition"](https://api.gov.au/standards/national_api_standards/getting-started.html#sample-openapi-definition), there are a number of links to sample OpenAPI specifications in both JSON and YAML formats, two of which are dedicated to OpenAPI v3.

When attempting to access these resources, a standard 404 is responded by an nginx server. I can see that these files are part of this repository so I assume they are intended to be available.

The two links in question which I am unable to access are as follows:
- https://api.gov.au/standards/national_api_standards/open-api-templates/v3.0/api-example-swagger-v1.4.json
- https://api.gov.au/standards/national_api_standards/open-api-templates/v3.0/api-example-swagger-v1.4.yml

I do not experience this issue when accessing the OpenAPI v2 examples. I am currently on Firefox 71.0 and have not yet experienced other issues with accessing documents. However, I have gone through very little of the document.

**Comment by colugo** [comment]
Thanks for the detailed issue @TomChapple. There was a copy-pasta in the links in the markdown files to the v3 templates. I've fixed it in the repo and redeployed the docs. 

The url's are:
- https://api.gov.au/standards/national_api_standards/open-api-templates/v3.0/api-example-openapi-v1.4.json
- https://api.gov.au/standards/national_api_standards/open-api-templates/v3.0/api-example-openapi-v1.4.yml

Alastair
