### ISSUE TITLE
Code examples go past the code box horizontally

### ISSUE THREAD

**Issue by wejrox** [apigovau/national-api-design-standards#15]
The code box doesn't have any css for overflow, so the text just continues forever. I'd strongly recommend adding `overflow-x: auto` to the `CODE` css class to enable horizontal text scrolling.

An example of the problem can be found here in the second code block:
https://api.gov.au/standards/national_api_standards/pagination.html#pagination-response

**Comment by colugo** [comment]
Thanks @wejrox, I've committed this and will redeploy shortly.
